### ISSUE TITLE
Variable in intent input create a TypeError

### ISSUE THREAD

**Issue by lodelestra** [openNLX/javascript#53]
## When
An intent contain a variable, and user try other intents on playground.
<img width="829" alt="screen shot 2018-10-04 at 15 34 06" src="https://user-images.githubusercontent.com/10141712/46477497-10ecda80-c7eb-11e8-8fef-dd29e5e84139.png">
## Then
Corresponding intent is not found and there is no response.
OpenNLX throw an error: `TypeError: Cannot read property 'next' of undefined`.
<img width="893" alt="screen shot 2018-10-04 at 15 26 24" src="https://user-images.githubusercontent.com/10141712/46477188-5e1c7c80-c7ea-11e8-8692-0f385fa79c8f.png">

**Comment by mikbry** [comment]
Not reproducted on last version
