### ISSUE TITLE
Input containing special char fail to match

### ISSUE THREAD

**Issue by jeffladiray** [openNLX/javascript#84]
The following test case fail because of the ending "?" 

```javascript
  it("Simple message with ?", async () => {
    const data = [{
      id: "1",
      name: "Hello",
      input: ["hello ?"],
      output: ["Hello Buddy!"],
    },
    {
      id: "2",
      name: "Yeaaah",
      input: ["yeaaah", "yeah"],
      output: ["Great!"],
    }];
    // Add intents to default
    intentsProvider.addIntents(data);
    // Parse a message
    let message = "Hello ?";
    let response = await resolver.parse(message, { context, intentsProvider });
    expect(response.message.text).to.equal("Hello Buddy!");
    message = "Yeah";
    response = await resolver.parse(message, { context, intentsProvider });
    expect(response.message.text).to.equal("Great!");
  });
```

Not sure why, but might be caused by intent input not being normalized ?

**Comment by mikbry** [comment]
It is a regression.
In previous release, extra special character was added to previous token. During refactoring, with Tokenizer and TokenStream, this behaviour was removed.
TODO
We need to add an option flag to Tokenizer to handle it.
In constructor add an options object containing a serie of value/bool, and addExtraCharsEnding=true by default.
In buildToken:
add next extra parameters (also in TokenStream)
 if addExtraCharsEnding and next is null or empty, and data.raw is not alphanum, append it to previous token. and return null token. treat null character in TokenStream addCurrentToken

**Comment by Thenkei** [comment]
I was looking at the code and I'm not sure that's a regression. The punctuation is kind of nasty for us.

Example of inputs variants.
- `What's up ?`
- `What's up?`
- `,What's, up ?`
- `What's up ???`
The only relevant information is `What's up`. I think we should look at the intent input normalization so we could have a more flexible matching (unbound to user punctuation).

**Comment by jeffladiray** [comment]
Agreed. Most of the lemmatizers drop those kind of useless punctuation characters since normalized output matching shouldn't look for those. Distinguishing 2 intents with or without the "?" or any kind if punctuation seems to be pretty hard.

@maali what's your point of view about it ?

**Comment by mikbry** [comment]
As other NLP tokenizers they could have different tokenizer based on the language or on the purpose. That's why I suggested some options parameters to fine tune the parsing of Tokenizer.
`what's up ?` 
in TokenStream raw tokens=`what's/up/?`
in Tokenizer + addExtraCharsEnding=true raw tokens=`what's/up?`
